'use strict';
(() => {
  const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d');
  const loading=document.querySelector('#loading'),place=document.querySelector('#place'),objective=document.querySelector('#objective'),prompt=document.querySelector('#prompt');
  const modal=document.querySelector('#modal'),tag=document.querySelector('#modal-tag'),title=document.querySelector('#modal-title'),body=document.querySelector('#modal-body'),choices=document.querySelector('#modal-choices');
  const visionButton=document.querySelector('#vision');
  const W=1600,H=900,assets={};
  const saved=(() => {try{return JSON.parse(localStorage.getItem('cybermycelium-adventure-v1')||'{}')}catch{return {}}})();
  const settings=(()=>{try{return {...{speed:'normal',text:'normal',hotspots:false,reduced:false},...JSON.parse(localStorage.getItem('cybermycelium-settings-v1')||'{}')}}catch{return {speed:'normal',text:'normal',hotspots:false,reduced:false}}})();
  const progress={memory:!!saved.memory,relay:!!saved.relay,specimen:!!saved.specimen,signal:!!saved.signal,node:!!saved.node,register:!!saved.register,witness:!!saved.witness,ending:saved.ending==='listen'||saved.ending==='seal'?saved.ending:null,chronicle:!!saved.chronicle,echo:!!saved.echo,seamCalibrated:!!saved.seamCalibrated,archSeen:!!saved.archSeen};
  let scene=['atrium','memory','seam'].includes(saved.scene)?saved.scene:'atrium',vision=false,hover=null,pending=null,last=0,elapsed=0,noticeUntil=0,introShown=false;
  const menu=document.querySelector('#menu'),keys=new Set();
  const hero={x:scene==='atrium'?730:1440,y:scene==='atrium'?770:720,to:null,facing:1,walking:false};
  const hotspots={
    atrium:[
      {id:'archive',name:'Архив эха',box:[90,370,430,640],go:[360,685]},
      {id:'register',name:'Реестр основания',box:[475,340,715,570],go:[615,675]},
      {id:'terminal',name:'Сигнальный терминал',box:[1080,510,1370,690],go:[1135,695]},
      {id:'gate',name:'Проход к камере памяти',box:[1430,310,1595,685],go:[1460,700]}
    ],
    memory:[
      {id:'specimen',name:'Споровый архив',box:[65,205,450,590],go:[390,675]},
      {id:'witness',name:'След свидетеля',box:[475,280,630,540],go:[595,675]},
      {id:'core',name:'Сердце памяти',box:[635,160,1080,575],go:[850,665]},
      {id:'console',name:'Пульт маршрута',box:[1140,390,1435,640],go:[1190,680]},
      {id:'back',name:'Вернуться в атриум',box:[1440,270,1590,615],go:[1465,690]}
    ],
    seam:[
      {id:'chronicle',name:'Хроника создателей',box:[115,110,545,605],go:[450,680]},
      {id:'rift',name:'Шов памяти',box:[700,115,995,605],go:[850,680]},
      {id:'calibration',name:'Пульт сопоставления',box:[1080,300,1370,630],go:[1190,690]},
      {id:'returnMemory',name:'Вернуться в камеру',box:[30,610,250,770],go:[175,720]},
      {id:'sealedArch',name:'Запечатанная ветвь',box:[1390,250,1590,595],go:[1450,690]}
    ]
  };
  function save(){try{localStorage.setItem('cybermycelium-adventure-v1',JSON.stringify({...progress,scene}))}catch{}}
  function saveSettings(){try{localStorage.setItem('cybermycelium-settings-v1',JSON.stringify(settings))}catch{}}
  function applySettings(){document.body.classList.toggle('large-text',settings.text==='large');document.querySelector('#move-speed').value=settings.speed;document.querySelector('#text-size').value=settings.text;document.querySelector('#always-hotspots').checked=!!settings.hotspots;document.querySelector('#reduced-motion').checked=!!settings.reduced}
  function showMenu(){hero.to=null;hero.walking=false;pending=null;keys.clear();document.querySelector('#menu-chapter').textContent=scene==='seam'?'ГЛАВА II · ШОВ РАЗРЫВА':'ГЛАВА I · НУЛЕВОЙ УЗЕЛ';document.querySelector('#menu-description').textContent=scene==='seam'?'Две записи одного события противоречат друг другу. Найдите след исправления и путь в запечатанную ветвь.':'Проводник восстанавливает память живой сети. Исследуйте зал, найдите записи и решите, отвечать ли неизвестному источнику.';menu.classList.add('show');menu.classList.remove('settings');document.querySelector('#continue').textContent=introShown||Object.values(progress).some(Boolean)?'ПРОДОЛЖИТЬ':'НАЧАТЬ ИГРУ';document.querySelector('#continue').focus()}
  function continueGame(){menu.classList.remove('show');menu.classList.remove('settings');last=0;if(!introShown){introShown=true;if(!Object.values(progress).some(Boolean))dialog('ПРОБУЖДЕНИЕ','Нулевой узел','Память фрагментирована. Маршрут нарушен. Вы — Проводник в атриуме живой вычислительной сети. Осмотрите окружение и восстановите ветвь.')}}
  document.querySelector('#menu-button').addEventListener('click',showMenu);
  document.querySelector('#continue').addEventListener('click',continueGame);
  document.querySelector('#settings-button').addEventListener('click',()=>{menu.classList.add('settings');document.querySelector('#move-speed').focus()});
  document.querySelector('#settings-back').addEventListener('click',()=>{menu.classList.remove('settings');document.querySelector('#continue').focus()});
  for(const [id,key,read] of [['move-speed','speed',el=>el.value],['text-size','text',el=>el.value],['always-hotspots','hotspots',el=>el.checked],['reduced-motion','reduced',el=>el.checked]])document.querySelector('#'+id).addEventListener('change',e=>{settings[key]=read(e.target);saveSettings();applySettings()});
  document.querySelector('#new-game').addEventListener('click',()=>{menu.classList.remove('show');dialog('НОВАЯ ИГРА','Начать заново?','Записи журнала, выбор финала и прохождение этой главы будут сброшены. Настройки управления сохранятся.',[{label:'СБРОСИТЬ ПРОХОЖДЕНИЕ',action:()=>{for(const key of Object.keys(progress))progress[key]=key==='ending'?null:false;scene='atrium';hero.x=730;hero.y=770;hero.to=null;pending=null;vision=false;visionButton.classList.remove('active');save();goal();close();introShown=false;showMenu()}},{label:'ОТМЕНА',action:()=>{close();showMenu()}}])});
  applySettings();
  function message(t,seconds=4){prompt.textContent=t;noticeUntil=elapsed+seconds}
  function goal(){place.textContent=scene==='atrium'?'НУЛЕВОЙ УЗЕЛ / АТРИУМ':scene==='memory'?'НУЛЕВОЙ УЗЕЛ / КАМЕРА ПАМЯТИ':'ГЛАВА II / ШОВ РАЗРЫВА';objective.textContent=scene==='seam'?(!progress.chronicle?'Прочитайте хронику создателей.':!progress.echo?'Исследуйте шов памяти.':!progress.seamCalibrated?'Сопоставьте две версии Разрыва.':progress.archSeen?'Глава II: причина подмены ещё неизвестна.':'Исследуйте запечатанную ветвь.'):progress.ending?'Вернитесь к сердцу памяти и пройдите к Шву Разрыва.':progress.node?'Сигнал пришёл извне. Решите, что делать с ним.':!progress.memory?'Найдите обрывок памяти в архиве.':!progress.relay?'Восстановите маршрут в терминале.':scene==='atrium'?'Пройдите в камеру памяти.':!progress.specimen?'Изучите споровый архив.':!progress.signal?'Настройте пульт маршрута.':'Пробудите сердце памяти.'}
  function dialog(kind,heading,text,buttons=[]){pending=null;tag.textContent=kind;title.textContent=heading;body.textContent=text;choices.replaceChildren();for(const b of buttons){let el=document.createElement('button');el.type='button';el.textContent=b.label;el.addEventListener('click',b.action);choices.append(el)}modal.classList.add('show');document.querySelector('#close').focus()}
  function close(){modal.classList.remove('show');goal()}
  document.querySelector('#close').addEventListener('click',close);
  const lore={
    origin:{title:'Основание',text:'Создатели выращивали вычислительную сеть в минеральных шахтах. Грибница удерживала данные не в одном центре: каждая ветвь могла помнить часть целого. Её называли PRIMUS MYCELIUM.'},
    rupture:{title:'Разрыв',text:'Однажды сеть получила ответ из области без известного адреса. Узлы начали сохранять несовместимые версии одного события. Создатели разорвали магистрали и запечатали память, чтобы остановить распространение ответа.'},
    echo:{title:'Фрагмент 01',text:'Последняя запись дежурного: «Сначала живая ткань, затем медь, затем память». Это порядок восстановления маршрута. В записи нет имени автора.'},
    witness:{title:'Свидетель',text:'След в камере не принадлежит создателям. Он оставлен уже после изоляции узла. Голос помнит Проводника и утверждает, что Разрыв был выбором, а не аварией.'},
    spore:{title:'Споровая память',text:'Споры переносят слабый отпечаток сигнала между отключёнными ветвями. Образец можно считать, не пробуждая соседние узлы.'},
    answer:{title:'Внешний ответ',text:'Источник не совпадает ни с одним адресом PRIMUS. Он ответил сразу после восстановления узла. Его природа и намерения неизвестны.'},
    chronicle:{title:'Хроника создателей',text:'Официальная лента называет Разрыв аварией: сначала расхождение сигналов, затем отключение магистралей. Последний лист имеет следы повторной печати.'},
    echo2:{title:'Эхо Шва',text:'Шов удерживает другую запись того же мгновения: сначала прозвучала команда отключить ветвь, а расхождение сигналов появилось позже. Голос не раскрывает, кто отдал команду.'},
    comparison:{title:'Сопоставление',text:'Две ленты несут одинаковую метку времени, но разный порядок событий. Пульт обнаружил исправление официальной хроники после изоляции. Кто изменил её и зачем — неизвестно.'}
  };
  const known=()=>[['origin',progress.register],['rupture',progress.relay],['echo',progress.memory],['witness',progress.witness],['spore',progress.specimen],['answer',progress.node],['chronicle',progress.chronicle],['echo2',progress.echo],['comparison',progress.seamCalibrated]].filter(([,yes])=>yes).map(([id])=>id);
  function journal(){const ids=known();dialog('ПОЛЕВОЙ ЖУРНАЛ','Записи Проводника',`Найдено ${ids.length} из 9 записей. ${progress.ending?'Решение сохранено: '+(progress.ending==='listen'?'принять ответ.':'изолировать канал.'):''} Выберите запись, чтобы прочитать её.`,ids.map(id=>({label:lore[id].title,action:()=>dialog('ЗАПИСЬ / '+lore[id].title,lore[id].title,lore[id].text,[{label:'К СПИСКУ',action:journal}])})))}
  document.querySelector('#journal').addEventListener('click',journal);
  visionButton.addEventListener('click',()=>{vision=!vision;visionButton.classList.toggle('active',vision);message(vision?'Связи проявились. Осмотрите отмеченные участки.':'Зрение сети отключено.',3)});
  const directions={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'};
  window.addEventListener('keydown',e=>{let key=e.key.toLowerCase();if(key==='escape'){if(menu.classList.contains('show')){if(menu.classList.contains('settings'))menu.classList.remove('settings');else continueGame()}else if(modal.classList.contains('show'))close();else showMenu();e.preventDefault();return}if(menu.classList.contains('show')||modal.classList.contains('show'))return;if(directions[key]){keys.add(directions[key]);e.preventDefault();return}if(e.repeat)return;if(key==='v')visionButton.click();if(key==='j')journal();if(key==='e'||key==='enter'){let h=hotspots[scene].reduce((best,item)=>{let d=Math.hypot(item.go[0]-hero.x,item.go[1]-hero.y);return !best||d<best.d?{h:item,d}:best},null);if(h&&h.d<160)walk(h.h.go[0],h.h.go[1],h.h);else message('Подойдите к предмету для осмотра.',2)}});
  window.addEventListener('keyup',e=>{let direction=directions[e.key.toLowerCase()];if(direction)keys.delete(direction)});
  window.addEventListener('blur',()=>keys.clear());
  function nextScene(name){scene=name;hero.x=name==='seam'?1350:name==='memory'?1430:1460;hero.y=720;hero.to=null;hover=null;save();goal();message(name==='seam'?'Глава II: две записи одного Разрыва.':name==='memory'?'Сеть хранит больше, чем показывает.':'Вы вернулись в атриум.',4)}
  const relayOrder=['ТКАНЬ','МЕДЬ','ПАМЯТЬ'];let relayStep=0;
  function puzzle(){relayStep=0;function show(){dialog('СИГНАЛЬНЫЙ ТЕРМИНАЛ','Восстановление маршрута',`Выберите порядок импульсов из архивной записи. Подключено: ${relayStep} из 3.`,relayOrder.map((label,index)=>({label,action:()=>{if(index===relayStep){relayStep++;if(relayStep===3){progress.relay=true;save();dialog('МАРШРУТ ВОССТАНОВЛЕН','Связь открыта','Мицелий принял последовательность. Под покрытием терминала обнаружен протокол Разрыва — новая запись в журнале. Дверь к камере памяти открыта.');goal()}else show()}else{relayStep=0;show();message('Последовательность сброшена.',3)}}})))}show()}
  function interact(id){
    if(id==='archive'){progress.memory=true;save();dialog('ЭХО ПАМЯТИ','Фрагмент 01',lore.echo.text+' Запись добавлена в журнал.');message('Фрагмент памяти получен. Подойдите к терминалу.',5)}
    if(id==='register'){progress.register=true;save();dialog('РЕЕСТР ОСНОВАНИЯ','PRIMUS MYCELIUM',lore.origin.text+' Запись добавлена в журнал.');}
    if(id==='terminal'){progress.memory?puzzle():dialog('СИГНАЛЬНЫЙ ТЕРМИНАЛ','Маршрут закрыт','Терминал ждёт утраченный порядок импульсов. След остался в архивном зале слева.')}
    if(id==='gate'){progress.relay?nextScene('memory'):dialog('СИГНАЛЬНЫЙ ШЛЮЗ','Нет маршрута','Дверь не узнаёт ваш сигнал. Восстановите маршрут в терминале.')}
    if(id==='witness'){progress.witness=true;save();dialog('ОСТАТОЧНЫЙ ГОЛОС','Свидетель','«Ты уже был здесь, Проводник. Они назвали это аварией, потому что боялись назвать выбором». Голос обрывается. Его след сохранён в журнале.');}
    if(id==='specimen'){progress.specimen=true;save();dialog('СПОРОВЫЙ АРХИВ','Живой образец','Споры удерживают отпечаток сигнала. Теперь пульт может сопоставить его с разорванной ветвью.');message('Образец считан. Осмотрите пульт справа.',5)}
    if(id==='console'){if(!progress.specimen){dialog('ПУЛЬТ МАРШРУТА','Нужен образец','В архиве слева хранится споровый отпечаток этого узла.');return}progress.signal=true;save();dialog('ПУЛЬТ МАРШРУТА','Канал открыт','Проводящие волокна нашли ответ. Подключитесь к сердцу памяти.');message('Канал открыт. Подойдите к центральному стволу.',5)}
    if(id==='core'){if(!progress.signal){dialog('СЕРДЦЕ ПАМЯТИ','Узел спит','Сначала считайте споровый образец и направьте его через пульт.');return}progress.node=true;save();const choose=(ending)=>{progress.ending=ending;save();goal();dialog('ГЛАВА I / ИСХОД',ending==='listen'?'Ответ принят':'Канал изолирован',ending==='listen'?'Вы открыли канал. Чужой сигнал произносит имя, которого вы не помните. Его источник остаётся за пределами узла.':'Вы закрыли канал. Перед затуханием сигнал оставил координаты неизвестной ветви в памяти узла.',[{label:'ИДТИ К ШВУ РАЗРЫВА',action:()=>{close();nextScene('seam')}}]);};if(progress.ending){dialog('СЕРДЦЕ ПАМЯТИ','Путь к Шву',progress.ending==='listen'?'Принятый сигнал указывает на шов в глубине памяти.':'Изолированный сигнал оставил координаты шва в глубине памяти.',[{label:'ИДТИ К ШВУ РАЗРЫВА',action:()=>{close();nextScene('seam')}}])}else dialog('УЗЕЛ 01 ВОССТАНОВЛЕН','Внешний ответ','Весь зал оживает. Незарегистрированный сигнал отвечает из области, которую сеть не помнит. Принять контакт или изолировать канал?',[{label:'СЛУШАТЬ ОТВЕТ',action:()=>choose('listen')},{label:'ИЗОЛИРОВАТЬ',action:()=>choose('seal')}]);message('УЗЕЛ 01 ВОССТАНОВЛЕН // ОБНАРУЖЕН ВНЕШНИЙ ОТВЕТ',8)}
    if(id==='chronicle'){progress.chronicle=true;save();dialog('ХРОНИКА СОЗДАТЕЛЕЙ','Официальная версия',lore.chronicle.text+' Запись добавлена в журнал.')}
    if(id==='rift'){progress.echo=true;save();dialog('ШОВ ПАМЯТИ','Иная последовательность',(progress.ending==='listen'?'Принятый сигнал удерживает голос в фокусе. ':'Изолированный канал оставил отпечаток голоса в спорах. ')+lore.echo2.text+' Запись добавлена в журнал.')}
    if(id==='calibration'){if(!progress.chronicle||!progress.echo){dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Недостаточно данных','Нужны официальная хроника слева и эхо в центре зала.');return}if(progress.seamCalibrated){dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','След исправления',lore.comparison.text);return}dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Найдите противоречие','Метки времени совпадают. Что различается в двух свидетельствах?',[{label:'ПОРЯДОК СОБЫТИЙ',action:()=>{progress.seamCalibrated=true;save();dialog('СОВПАДЕНИЕ НАРУШЕНО','Исправленная хроника',lore.comparison.text+' Арка справа реагирует на восстановленную запись.');goal()}},{label:'ВРЕМЯ СОБЫТИЯ',action:()=>dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Метка совпадает','Обе ленты несут одинаковую метку времени. Вернитесь к пульту и сравните содержание.')},{label:'НАЗВАНИЕ УЗЛА',action:()=>dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Адрес совпадает','Обе ленты относятся к Нулевому узлу. Вернитесь к пульту и сравните содержание.')}])}
    if(id==='sealedArch'){if(!progress.seamCalibrated){dialog('ЗАПЕЧАТАННАЯ ВЕТВЬ','Нет согласованного следа','Арка не откроется, пока пульт не сопоставит две записи Разрыва.');return}progress.archSeen=true;save();goal();dialog('ГЛАВА II / ШОВ РАЗРЫВА','Третья запись','Арка открывает лишь узкую щель. За ней виден третий носитель памяти, которого нет в реестре создателей. Сеть не сообщает, кому он принадлежит. Продолжение следует.')}
    if(id==='returnMemory')nextScene('memory');
    if(id==='back')nextScene('atrium');goal()
  }
  function point(e){let r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
  function hit(p){return hotspots[scene].find(h=>p.x>=h.box[0]&&p.x<=h.box[2]&&p.y>=h.box[1]&&p.y<=h.box[3])}
  function walk(x,y,h=null){hero.to={x:Math.max(90,Math.min(1510,x)),y:Math.max(625,Math.min(825,y))};pending=h}
  canvas.addEventListener('pointermove',e=>{hover=hit(point(e));canvas.style.cursor=hover?'pointer':'crosshair'});
  canvas.addEventListener('pointerleave',()=>{hover=null});
  canvas.addEventListener('pointerdown',e=>{if(modal.classList.contains('show')||menu.classList.contains('show'))return;let p=point(e),h=hit(p);if(h){walk(h.go[0],h.go[1],h);message(h.name,2)}else if(p.y>560){walk(p.x,p.y);message('Проводник идёт...',1.5)}else message('Здесь нет прохода. Выберите участок пола.',2)});
  function drawHero(){let scale=.68+(hero.y-625)/650,bob=hero.walking&&!settings.reduced?Math.sin(elapsed*12)*2:0,x=hero.x,y=hero.y+bob;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#050c0c99';ctx.beginPath();ctx.ellipse(0,3,25,7,0,0,Math.PI*2);ctx.fill();ctx.lineCap='round';ctx.strokeStyle='#0a1112';ctx.lineWidth=8;let stride=hero.walking&&!settings.reduced?Math.sin(elapsed*12)*8:0;ctx.beginPath();ctx.moveTo(-7,-14);ctx.lineTo(-9+stride,0);ctx.moveTo(7,-14);ctx.lineTo(9-stride,0);ctx.stroke();ctx.fillStyle='#0b1618';ctx.beginPath();ctx.moveTo(-16,-64);ctx.lineTo(14,-63);ctx.lineTo(19,-14);ctx.lineTo(-17,-15);ctx.closePath();ctx.fill();ctx.fillStyle='#34423d';ctx.fillRect(-14,-62,5,41);ctx.fillStyle='#111f23';ctx.beginPath();ctx.ellipse(0,-71,12,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6bbbc2';ctx.fillRect(hero.facing>0?2:-10,-75,8,3);ctx.fillStyle='#c99959';ctx.fillRect(-20,-48,4,11);ctx.restore()}
  function drawHotspots(){for(const h of hotspots[scene]){if(!vision&&!settings.hotspots&&hover!==h)continue;let x=(h.box[0]+h.box[2])/2,y=h.box[3]-32,pulse=settings.reduced?0:3+Math.sin(elapsed*3)*2;ctx.save();ctx.strokeStyle=vision?'#91d2d1':'#ebc58b';ctx.fillStyle=vision?'#b4eceb':'#f8dfaa';ctx.lineWidth=2;ctx.globalAlpha=hover===h?1:.72;ctx.beginPath();ctx.arc(x,y,13+pulse,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();if(hover===h){ctx.font='18px monospace';let measure=ctx.measureText(h.name).width;ctx.fillStyle='#0b181add';ctx.fillRect(x-measure/2-10,y-51,measure+20,30);ctx.fillStyle='#f4e6c8';ctx.fillText(h.name,x-measure/2,y-30)}ctx.restore()}}
  function render(){ctx.fillStyle='#101819';ctx.fillRect(0,0,W,H);let img=assets[scene];if(img&&img.complete&&img.naturalWidth)ctx.drawImage(img,0,0,W,H);if(progress.node&&scene==='memory'){ctx.fillStyle='rgba(224,158,75,.08)';ctx.fillRect(0,0,W,H)}drawHotspots();drawHero();if(!settings.reduced)for(let i=0;i<35;i++){let x=(i*317+elapsed*(i%3+1)*8)%W,y=(i*197+Math.sin(elapsed+i)*25)%H;ctx.fillStyle='#dfcc9c60';ctx.fillRect(x,y,2,2)}}
  function update(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;const speed=({slow:180,normal:285,fast:440})[settings.speed]||285;if(!menu.classList.contains('show')&&!modal.classList.contains('show')){elapsed+=dt;let mx=Number(keys.has('right'))-Number(keys.has('left')),my=Number(keys.has('down'))-Number(keys.has('up'));if(mx||my){hero.to=null;pending=null;let length=Math.hypot(mx,my);hero.x=Math.max(90,Math.min(1510,hero.x+mx/length*speed*dt));hero.y=Math.max(625,Math.min(825,hero.y+my/length*speed*dt));if(mx)hero.facing=mx>0?1:-1;hero.walking=true}else if(hero.to){let dx=hero.to.x-hero.x,dy=hero.to.y-hero.y,d=Math.hypot(dx,dy),step=speed*dt;if(d<=step+3){hero.x=hero.to.x;hero.y=hero.to.y;hero.to=null;hero.walking=false;if(pending){let h=pending;pending=null;interact(h.id)}}else{hero.x+=dx/d*step;hero.y+=dy/d*step;hero.facing=dx>=0?1:-1;hero.walking=true}}else hero.walking=false;if(noticeUntil&&elapsed>noticeUntil){noticeUntil=0;prompt.textContent=vision?'Связи проявились. Выберите отмеченный объект.':'Нажмите на пол, чтобы идти. Осмотрите предметы.'}}render();requestAnimationFrame(update)}
  function load(name,src){return new Promise(resolve=>{let img=new Image();assets[name]=img;img.onload=resolve;img.onerror=()=>{message('Фон не загрузился. Проверьте соединение.',8);resolve()};img.src=src})}
  goal();Promise.all([load('atrium','./assets/atrium.webp'),load('memory','./assets/memory.webp'),load('seam','./assets/seam.webp')]).then(()=>{loading.classList.add('hidden');showMenu();requestAnimationFrame(update)});
})();
