'use strict';
(() => {
  const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d');
  const loading=document.querySelector('#loading'),place=document.querySelector('#place'),objective=document.querySelector('#objective'),prompt=document.querySelector('#prompt');
  const modal=document.querySelector('#modal'),tag=document.querySelector('#modal-tag'),title=document.querySelector('#modal-title'),body=document.querySelector('#modal-body'),choices=document.querySelector('#modal-choices'),detail=document.querySelector('#detail'),detailCtx=detail.getContext('2d');
  const visionButton=document.querySelector('#vision');
  const W=1600,H=900,assets={};
  const saved=(() => {try{return JSON.parse(localStorage.getItem('cybermycelium-adventure-v1')||'{}')}catch{return {}}})();
  const settings=(()=>{try{return {...{speed:'normal',text:'normal',hotspots:false,reduced:false},...JSON.parse(localStorage.getItem('cybermycelium-settings-v1')||'{}')}}catch{return {speed:'normal',text:'normal',hotspots:false,reduced:false}}})();
  const hasOldSave=Object.keys(saved).length>0;
  const progress={ashSignal:!!saved.ashSignal,ashSpores:!!saved.ashSpores,ashCompared:!!saved.ashCompared,ashPassage:!!saved.ashPassage||hasOldSave&&!('ashSignal' in saved),membraneSeen:!!saved.membraneSeen,contactsSeen:!!saved.contactsSeen,adapter:!!saved.adapter||!!saved.relay,memory:!!saved.memory,relay:!!saved.relay,specimen:!!saved.specimen,signal:!!saved.signal,node:!!saved.node,register:!!saved.register,witness:!!saved.witness,ending:saved.ending==='listen'||saved.ending==='seal'?saved.ending:null,chronicle:!!saved.chronicle,echo:!!saved.echo,seamCalibrated:!!saved.seamCalibrated,archSeen:!!saved.archSeen};
  let scene=['ash','atrium','interface','memory','seam'].includes(saved.scene)?saved.scene:hasOldSave?'atrium':'ash',vision=false,hover=null,pending=null,last=0,elapsed=0,noticeUntil=0,introShown=false,activeInspection=null;
  const menu=document.querySelector('#menu'),worldMap=document.querySelector('#world-map'),keys=new Set();
  const hero={x:scene==='ash'?700:scene==='atrium'?730:scene==='interface'?240:1440,y:scene==='ash'||scene==='atrium'?770:720,to:null,facing:1,walking:false};
  const hotspots={
    ash:[
      {id:'recorder',name:'Полевой прибор',box:[50,80,255,505],go:[255,715]},
      {id:'ashRoots',name:'Споры в пепле',box:[575,210,1060,625],go:[825,705]},
      {id:'ashGate',name:'Вход в Нулевой узел',box:[1260,70,1595,575],go:[1400,710]}
    ],
    atrium:[
      {id:'sideDoor',name:'Камера сопряжения',box:[5,155,290,370],go:[255,690]},
      {id:'archive',name:'Архив эха',box:[90,370,430,640],go:[360,685]},
      {id:'register',name:'Реестр основания',box:[475,340,715,570],go:[615,675]},
      {id:'terminal',name:'Сигнальный терминал',box:[1080,510,1370,690],go:[1135,695]},
      {id:'gate',name:'Проход к камере памяти',box:[1430,310,1595,685],go:[1460,700]},
      {id:'surface',name:'Выход к Пепельным террасам',box:[5,640,245,835],go:[210,730]}
    ],
    interface:[
      {id:'membrane',name:'Живая мембрана',box:[320,70,825,545],go:[580,695]},
      {id:'workbench',name:'Ложе переходника',box:[850,345,1185,560],go:[1030,700]},
      {id:'contacts',name:'Медные контакты',box:[1220,35,1555,480],go:[1270,690]},
      {id:'returnAtrium',name:'Вернуться в Нулевой узел',box:[5,90,295,570],go:[190,705]}
    ],
    memory:[
      {id:'specimen',name:'Споровый архив',box:[65,205,450,590],go:[390,675]},
      {id:'witness',name:'След свидетеля',box:[475,280,630,540],go:[595,675]},
      {id:'core',name:'Сердце памяти',box:[635,160,1080,575],go:[850,665]},
      {id:'console',name:'Пульт маршрута',box:[1140,390,1435,640],go:[1190,680]},
      {id:'back',name:'Вернуться в атриум',box:[1440,270,1590,615],go:[1465,690]}
    ],
    seam:[
      {id:'chronicle',name:'Хроника создателей',box:[115,110,545,605],go:[450,680]},
      {id:'rift',name:'Шов памяти',box:[700,115,995,605],go:[850,680]},
      {id:'calibration',name:'Пульт сопоставления',box:[1080,300,1370,630],go:[1190,690]},
      {id:'returnMemory',name:'Вернуться в камеру',box:[30,610,250,770],go:[175,720]},
      {id:'sealedArch',name:'Запечатанная ветвь',box:[1390,250,1590,595],go:[1450,690]}
    ]
  };
  function save(){try{localStorage.setItem('cybermycelium-adventure-v1',JSON.stringify({...progress,scene}))}catch{}}
  function saveSettings(){try{localStorage.setItem('cybermycelium-settings-v1',JSON.stringify(settings))}catch{}}
  function applySettings(){document.body.classList.toggle('large-text',settings.text==='large');document.querySelector('#move-speed').value=settings.speed;document.querySelector('#text-size').value=settings.text;document.querySelector('#always-hotspots').checked=!!settings.hotspots;document.querySelector('#reduced-motion').checked=!!settings.reduced}
  function showMenu(){hero.to=null;hero.walking=false;pending=null;keys.clear();document.querySelector('#menu-chapter').textContent=scene==='ash'?'ДАЛЬНЯЯ ПОВЕРХНОСТЬ · ПРИБЫТИЕ':scene==='interface'?'НУЛЕВОЙ УЗЕЛ · КАМЕРА СОПРЯЖЕНИЯ':scene==='seam'?'ВНУТРЕННЕЕ КОЛЬЦО · ПУТЬ К ЦЕНТРУ':scene==='memory'?'СКЛЕП ПАМЯТИ · ПУТЬ К ЦЕНТРУ':'ВНЕШНИЙ ПРЕДЕЛ · ПУТЬ К ЦЕНТРУ';document.querySelector('#menu-description').textContent='Маг с другой планеты исследует грибницу, соединяющую дальние участки гробницы с её закрытой сердцевиной.';menu.classList.add('show');menu.classList.remove('settings');document.querySelector('#continue').textContent=introShown||Object.values(progress).some(Boolean)?'ПРОДОЛЖИТЬ':'НАЧАТЬ ИГРУ';document.querySelector('#continue').focus()}
  function continueGame(){menu.classList.remove('show');menu.classList.remove('settings');last=0;if(!introShown){introShown=true;if(!Object.values(progress).some(Boolean))dialog('ПРИБЫТИЕ',scene==='ash'?'Пепельные террасы':'Нулевой узел',scene==='ash'?'Вы — маг в чёрном балахоне. Вы прибыли с другой планеты изучить грибницу под этими террасами. Перед посадкой вы послали сюда исследовательский сигнал. Проверьте собственную запись и живой след в пепле, прежде чем войти в гробницу.':'Вы — маг в чёрном балахоне, прибывший с другой планеты изучить местную грибницу. У внешнего предела гробницы нити мицелия связывают далёкие колонии с закрытой сердцевиной. Следуйте внутрь и выясните, что скрывает сеть.')}}
  document.querySelector('#menu-button').addEventListener('click',showMenu);
  document.querySelector('#continue').addEventListener('click',continueGame);
  document.querySelector('#settings-button').addEventListener('click',()=>{menu.classList.add('settings');document.querySelector('#move-speed').focus()});
  document.querySelector('#settings-back').addEventListener('click',()=>{menu.classList.remove('settings');document.querySelector('#continue').focus()});
  for(const [id,key,read] of [['move-speed','speed',el=>el.value],['text-size','text',el=>el.value],['always-hotspots','hotspots',el=>el.checked],['reduced-motion','reduced',el=>el.checked]])document.querySelector('#'+id).addEventListener('change',e=>{settings[key]=read(e.target);saveSettings();applySettings()});
  document.querySelector('#new-game').addEventListener('click',()=>{menu.classList.remove('show');dialog('НОВАЯ ИГРА','Начать заново?','Записи журнала, выбор финала и прохождение этой главы будут сброшены. Настройки управления сохранятся.',[{label:'СБРОСИТЬ ПРОХОЖДЕНИЕ',action:()=>{for(const key of Object.keys(progress))progress[key]=key==='ending'?null:false;scene='ash';hero.x=700;hero.y=770;hero.to=null;pending=null;vision=false;visionButton.classList.remove('active');save();goal();close();introShown=false;showMenu()}},{label:'ОТМЕНА',action:()=>{close();showMenu()}}])});
  applySettings();
  function showMap(){for(const el of document.querySelectorAll('.map-node')){const node=el.dataset.scene;el.classList.toggle('current',node===scene);el.classList.toggle('locked',node==='center'||node==='memory'&&!progress.relay||node==='seam'&&!progress.ending||node==='atrium'&&scene==='ash'&&!progress.ashCompared&&!progress.ashPassage)}keys.clear();worldMap.classList.add('show');document.querySelector('#map-close').focus()}
  function closeMap(){worldMap.classList.remove('show');last=0}
  document.querySelector('#map-button').addEventListener('click',showMap);document.querySelector('#map-close').addEventListener('click',closeMap);
  function message(t,seconds=4){prompt.textContent=t;noticeUntil=elapsed+seconds}
  function goal(){place.textContent=scene==='ash'?'ДАЛЬНЯЯ ПОВЕРХНОСТЬ / ПЕПЕЛЬНЫЕ ТЕРРАСЫ':scene==='interface'?'НУЛЕВОЙ УЗЕЛ / КАМЕРА СОПРЯЖЕНИЯ':scene==='atrium'?'ВНЕШНИЙ ПРЕДЕЛ / НУЛЕВОЙ УЗЕЛ':scene==='memory'?'ВНУТРЕННИЙ ПУТЬ / СКЛЕП ПАМЯТИ':'ВНУТРЕННЕЕ КОЛЬЦО / ШОВ РАЗРЫВА';objective.textContent=scene==='ash'?(!progress.ashSignal?'Проверьте свой полевой прибор.':!progress.ashSpores?'Считайте споры у входа.':!progress.ashCompared?'Сопоставьте следы в приборе.':'Войдите в Нулевой узел.'):scene==='interface'?(!progress.membraneSeen?'Изучите живую мембрану.':!progress.contactsSeen?'Осмотрите медные контакты.':!progress.adapter?'Соберите переходник на ложе.':'Вернитесь с переходником к терминалу.'):scene==='seam'?(!progress.chronicle?'Прочитайте хронику создателей.':!progress.echo?'Исследуйте шов памяти.':!progress.seamCalibrated?'Сопоставьте две версии Разрыва.':progress.archSeen?'Глава II: причина подмены ещё неизвестна.':'Исследуйте запечатанную ветвь.'):progress.ending?'Вернитесь к сердцу памяти и пройдите к Шву Разрыва.':progress.node?'Сигнал пришёл извне. Решите, что делать с ним.':!progress.memory?'Найдите обрывок памяти в архиве.':!progress.adapter?'Найдите способ подключиться к терминалу в боковой камере.':!progress.relay?'Восстановите маршрут в терминале.':scene==='atrium'?'Пройдите в камеру памяти.':!progress.specimen?'Изучите споровый архив.':!progress.signal?'Настройте пульт маршрута.':'Пробудите сердце памяти.'}
  function dialog(kind,heading,text,buttons=[]){pending=null;tag.textContent=kind;title.textContent=heading;body.textContent=text;choices.replaceChildren();for(const b of buttons){let el=document.createElement('button');el.type='button';el.textContent=b.label;el.addEventListener('click',b.action);choices.append(el)}const img=assets[scene];const showDetail=!!(activeInspection&&img&&img.complete&&img.naturalWidth);modal.classList.toggle('inspect',showDetail);if(showDetail){const b=activeInspection.box,cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2,cw=Math.max(380,Math.min(760,(b[2]-b[0])*1.4)),ch=cw*420/1000,sx=Math.max(0,Math.min(W-cw,cx-cw/2)),sy=Math.max(0,Math.min(H-ch,cy-ch/2));detailCtx.drawImage(img,sx,sy,cw,ch,0,0,1000,420)}modal.classList.add('show');document.querySelector('#close').focus()}
  function close(){modal.classList.remove('show');modal.classList.remove('inspect');activeInspection=null;goal()}
  document.querySelector('#close').addEventListener('click',close);
  const lore={
    traveler:{title:'Прибытие мага',text:'Я прибыл с другой планеты, чтобы изучить мицелий, связывающий эту гробницу и далёкие колонии. Мой чёрный балахон и ремесло мага здесь чужие. Почему сеть или её свидетель будто бы знает меня — вопрос, на который пока нет ответа.'},
    fieldSignal:{title:'Мой ранний сигнал',text:'Полевой прибор сохранил исходящий исследовательский импульс, отправленный к планете до моей посадки. В локальном архиве нет входящего ответа за тот период. Это подтверждает отправку, но не доказывает, кто мог услышать сигнал.'},
    ashTrace:{title:'След в пепле',text:'Споры в пепле несут изменённый отзвук того же ритма. Они пришли по живым нитям со стороны Нулевого узла. Это независимый материальный след, но он не раскрывает источник будущего ответа.'},
    membrane:{title:'Живая мембрана',text:'В боковой камере Нулевого узла мембрана отвечает тремя фазами: изолировать открытый контакт, выровнять ритм ткани, лишь затем замкнуть медь. Голая рука или магический импульс не заменят согласования сред.'},
    contacts:{title:'Медный контакт',text:'На медном гнезде сохранился след обожжённого проводника. Прямое соединение губило живой слой; переходник должен удерживать между ним и металлом биокерамическую прослойку.'},
    coupling:{title:'Переходник',text:'В ложе собран переносной биокерамический переходник. Он переводит медленные химические импульсы ткани в читаемый терминалом ритм. Это инструмент связи с устройствами PRIMUS, а не ключ к чужим воспоминаниям.'},
    origin:{title:'Основание',text:'Создатели выращивали PRIMUS MYCELIUM в минеральных шахтах. Нити связали далёкие колонии, хранилища и сердцевину общей гробницы. Каждая ветвь помнит часть целого; путь внутрь восстанавливается по следам памяти.'},
    rupture:{title:'Разрыв',text:'Однажды сеть получила ответ из области без известного адреса. Узлы начали сохранять несовместимые версии одного события. Создатели разорвали магистрали и запечатали память, чтобы остановить распространение ответа.'},
    echo:{title:'Фрагмент 01',text:'Последняя запись дежурного: «Сначала живая ткань, затем медь, затем память». Это порядок восстановления маршрута. В записи нет имени автора.'},
    witness:{title:'Свидетель',text:'След в камере не принадлежит создателям. Он оставлен уже после изоляции узла. Голос помнит Проводника и утверждает, что Разрыв был выбором, а не аварией.'},
    spore:{title:'Споровая память',text:'Споры переносят слабый отпечаток сигнала между отключёнными ветвями. Образец можно считать, не пробуждая соседние узлы.'},
    answer:{title:'Внешний ответ',text:'Источник не совпадает ни с одним адресом PRIMUS. Он ответил сразу после восстановления узла. Его природа и намерения неизвестны.'},
    chronicle:{title:'Хроника создателей',text:'Официальная лента называет Разрыв аварией: сначала расхождение сигналов, затем отключение магистралей. Последний лист имеет следы повторной печати.'},
    echo2:{title:'Эхо Шва',text:'Шов удерживает другую запись того же мгновения: сначала прозвучала команда отключить ветвь, а расхождение сигналов появилось позже. Голос не раскрывает, кто отдал команду.'},
    comparison:{title:'Сопоставление',text:'Две ленты несут одинаковую метку времени, но разный порядок событий. Пульт обнаружил исправление официальной хроники после изоляции. Кто изменил её и зачем — неизвестно.'}
  };
  const known=()=>[['traveler',true],['fieldSignal',progress.ashSignal],['ashTrace',progress.ashSpores],['membrane',progress.membraneSeen],['contacts',progress.contactsSeen],['coupling',progress.adapter],['origin',progress.register],['rupture',progress.relay],['echo',progress.memory],['witness',progress.witness],['spore',progress.specimen],['answer',progress.node],['chronicle',progress.chronicle],['echo2',progress.echo],['comparison',progress.seamCalibrated]].filter(([,yes])=>yes).map(([id])=>id);
  function journal(){const ids=known();dialog('ПОЛЕВОЙ ЖУРНАЛ','Записи Проводника',`Найдено ${ids.length} из ${Object.keys(lore).length} записей. ${progress.ending?'Решение сохранено: '+(progress.ending==='listen'?'принять ответ.':'изолировать канал.'):''} Выберите запись, чтобы прочитать её.`,ids.map(id=>({label:lore[id].title,action:()=>dialog('ЗАПИСЬ / '+lore[id].title,lore[id].title,lore[id].text,[{label:'К СПИСКУ',action:journal}])})))}
  document.querySelector('#journal').addEventListener('click',journal);
  visionButton.addEventListener('click',()=>{vision=!vision;visionButton.classList.toggle('active',vision);message(vision?'Связи проявились. Осмотрите отмеченные участки.':'Зрение сети отключено.',3)});
  const directions={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'};
  window.addEventListener('keydown',e=>{let key=e.key.toLowerCase();if(key==='escape'){if(worldMap.classList.contains('show'))closeMap();else if(menu.classList.contains('show')){if(menu.classList.contains('settings'))menu.classList.remove('settings');else continueGame()}else if(modal.classList.contains('show'))close();else showMenu();e.preventDefault();return}if(menu.classList.contains('show')||modal.classList.contains('show')||worldMap.classList.contains('show'))return;if(key==='m'&&!e.repeat){showMap();return}if(directions[key]){keys.add(directions[key]);e.preventDefault();return}if(e.repeat)return;if(key==='v')visionButton.click();if(key==='j')journal();if(key==='e'||key==='enter'){let h=hotspots[scene].reduce((best,item)=>{let d=Math.hypot(item.go[0]-hero.x,item.go[1]-hero.y);return !best||d<best.d?{h:item,d}:best},null);if(h&&h.d<160)walk(h.h.go[0],h.h.go[1],h.h);else message('Подойдите к предмету для осмотра.',2)}});
  window.addEventListener('keyup',e=>{let direction=directions[e.key.toLowerCase()];if(direction)keys.delete(direction)});
  window.addEventListener('blur',()=>keys.clear());
  function nextScene(name){activeInspection=null;scene=name;hero.x=name==='ash'?1280:name==='atrium'?350:name==='interface'?220:name==='seam'?1350:1430;hero.y=720;hero.to=null;hover=null;save();goal();message(name==='ash'?'Вы вышли на Пепельные террасы.':name==='interface'?'Боковая камера хранит способ сопряжения живой ткани и меди.':name==='seam'?'Нити сходятся к Шву Разрыва.':name==='memory'?'Нити ведут глубже, к склепу памяти.':'Вы вошли в Нулевой узел.',4)}
  const relayOrder=['ТКАНЬ','МЕДЬ','ПАМЯТЬ'];let relayStep=0;
  function puzzle(){relayStep=0;function show(){dialog('СИГНАЛЬНЫЙ ТЕРМИНАЛ','Восстановление маршрута',`Выберите порядок импульсов из архивной записи. Подключено: ${relayStep} из 3.`,relayOrder.map((label,index)=>({label,action:()=>{if(index===relayStep){relayStep++;if(relayStep===3){progress.relay=true;save();dialog('МАРШРУТ ВОССТАНОВЛЕН','Связь открыта','Мицелий принял последовательность. Под покрытием терминала обнаружен протокол Разрыва — новая запись в журнале. Дверь к камере памяти открыта.');goal()}else show()}else{relayStep=0;show();message('Последовательность сброшена.',3)}}})))}show()}
  const interfaceOrder=['ИЗОЛИРОВАТЬ','ВЫРОВНЯТЬ РИТМ','ЗАМКНУТЬ КОНТАКТ'];let interfaceStep=0;
  function assembleAdapter(){if(progress.adapter){dialog('ЛОЖЕ СОПРЯЖЕНИЯ','Переходник взят',lore.coupling.text);return}if(!progress.membraneSeen||!progress.contactsSeen){dialog('ЛОЖЕ СОПРЯЖЕНИЯ','Неизвестный протокол','Сначала изучите живую мембрану слева и медные контакты справа. Разные материалы оставили разные следы.');return}interfaceStep=0;function show(){dialog('ЛОЖЕ СОПРЯЖЕНИЯ','Собрать переходник',`В каком порядке соединить ткань с медью? Выполнено: ${interfaceStep} из 3.`,interfaceOrder.map((label,index)=>({label,action:()=>{if(index===interfaceStep){interfaceStep++;if(interfaceStep===3){progress.adapter=true;save();goal();dialog('ПЕРЕХОДНИК СОБРАН','Биокерамический мост',lore.coupling.text+' Вернитесь к терминалу в Нулевом узле.')}else show()}else{interfaceStep=0;show();message('Контакт неустойчив. Прослойка вернулась в исходное положение.',4)}}})))}show()}
  function interact(id){
    activeInspection=hotspots[scene].find(h=>h.id===id)||null;
    if(id==='recorder'){if(!progress.ashSignal){progress.ashSignal=true;save();dialog('ПОЛЕВОЙ ПРИБОР','Мой ранний сигнал',lore.fieldSignal.text+' Запись добавлена в журнал.')}else if(progress.ashSpores&&!progress.ashCompared){dialog('ПОЛЕВОЙ ПРИБОР','Сопоставить следы','Прибор хранит отправленный вами ритм. Споры у входа удержали изменённый отзвук. Сравнить их, не приписывая пока ответ конкретному источнику?',[{label:'СОПОСТАВИТЬ РИТМЫ',action:()=>{progress.ashCompared=true;save();goal();dialog('СЛЕД СВЯЗИ','Направление установлено','Ритмы родственны, но не тождественны. Споры пришли по нити из Нулевого узла. Это путь для исследования, а не доказательство, кто или что ответило. Проход открыт.')}}])}else dialog('ПОЛЕВОЙ ПРИБОР','Мой ранний сигнал',lore.fieldSignal.text+(progress.ashCompared?' Направление входа отмечено.':' Для сравнения нужен живой след из пепла.'))}
    if(id==='ashRoots'){progress.ashSpores=true;save();dialog('СЧИТЫВАНИЕ СПОР','След в пепле',lore.ashTrace.text+' Запись добавлена в журнал.');message('Сопоставьте след с личной записью в приборе.',5)}
    if(id==='ashGate'){progress.ashCompared||progress.ashPassage?nextScene('atrium'):dialog('ВХОД В ГРОБНИЦУ','Нить без направления','Мицелий ведёт внутрь, но ещё не ясно, какой отзвук ваш. Исследуйте прибор и споры, затем сопоставьте их.')}
    if(id==='sideDoor')nextScene('interface');
    if(id==='membrane'){progress.membraneSeen=true;save();dialog('ЧТЕНИЕ ТКАНИ','Живая мембрана',lore.membrane.text+' Запись добавлена в журнал.');goal()}
    if(id==='contacts'){progress.contactsSeen=true;save();dialog('МЕДНОЕ ГНЕЗДО','Обожжённый след',lore.contacts.text+' Запись добавлена в журнал.');goal()}
    if(id==='workbench')assembleAdapter();
    if(id==='returnAtrium')nextScene('atrium');
    if(id==='archive'){progress.memory=true;save();dialog('ЭХО ПАМЯТИ','Фрагмент 01',lore.echo.text+' Запись добавлена в журнал.');message('Фрагмент памяти получен. Подойдите к терминалу.',5)}
    if(id==='register'){progress.register=true;save();dialog('РЕЕСТР ОСНОВАНИЯ','PRIMUS MYCELIUM',lore.origin.text+' Запись добавлена в журнал.');}
    if(id==='terminal'){!progress.adapter?dialog('СИГНАЛЬНЫЙ ТЕРМИНАЛ','Нечитаемый интерфейс','Ваше ремесло различает живой след, но гнездо PRIMUS не принимает прямой сигнал. Найдите переходник в боковой камере слева; голым касанием нити не соединить.'):progress.memory?puzzle():dialog('СИГНАЛЬНЫЙ ТЕРМИНАЛ','Маршрут закрыт','Переходник распознан. Терминал ждёт утраченный порядок импульсов. След остался в архивном зале слева.')}
    if(id==='gate'){progress.relay?nextScene('memory'):dialog('СИГНАЛЬНЫЙ ШЛЮЗ','Нет маршрута','Дверь не узнаёт ваш сигнал. Восстановите маршрут в терминале.')}
    if(id==='witness'){progress.witness=true;save();dialog('ОСТАТОЧНЫЙ ГОЛОС','Свидетель','«Ты уже был здесь, Проводник. Они назвали это аварией, потому что боялись назвать выбором». Голос обрывается. Его след сохранён в журнале.');}
    if(id==='specimen'){progress.specimen=true;save();dialog('СПОРОВЫЙ АРХИВ','Живой образец','Споры удерживают отпечаток сигнала. Теперь пульт может сопоставить его с разорванной ветвью.');message('Образец считан. Осмотрите пульт справа.',5)}
    if(id==='console'){if(!progress.specimen){dialog('ПУЛЬТ МАРШРУТА','Нужен образец','В архиве слева хранится споровый отпечаток этого узла.');return}progress.signal=true;save();dialog('ПУЛЬТ МАРШРУТА','Канал открыт','Проводящие волокна нашли ответ. Подключитесь к сердцу памяти.');message('Канал открыт. Подойдите к центральному стволу.',5)}
    if(id==='core'){if(!progress.signal){dialog('СЕРДЦЕ ПАМЯТИ','Узел спит','Сначала считайте споровый образец и направьте его через пульт.');return}progress.node=true;save();const choose=(ending)=>{progress.ending=ending;save();goal();dialog('ГЛАВА I / ИСХОД',ending==='listen'?'Ответ принят':'Канал изолирован',ending==='listen'?'Вы открыли канал. Чужой сигнал произносит имя, которого вы не помните. Его источник остаётся за пределами узла.':'Вы закрыли канал. Перед затуханием сигнал оставил координаты неизвестной ветви в памяти узла.',[{label:'ИДТИ К ШВУ РАЗРЫВА',action:()=>{close();nextScene('seam')}}]);};if(progress.ending){dialog('СЕРДЦЕ ПАМЯТИ','Путь к Шву',progress.ending==='listen'?'Принятый сигнал указывает на шов в глубине памяти.':'Изолированный сигнал оставил координаты шва в глубине памяти.',[{label:'ИДТИ К ШВУ РАЗРЫВА',action:()=>{close();nextScene('seam')}}])}else dialog('УЗЕЛ 01 ВОССТАНОВЛЕН','Внешний ответ','Весь зал оживает. Незарегистрированный сигнал отвечает из области, которую сеть не помнит. Принять контакт или изолировать канал?',[{label:'СЛУШАТЬ ОТВЕТ',action:()=>choose('listen')},{label:'ИЗОЛИРОВАТЬ',action:()=>choose('seal')}]);message('УЗЕЛ 01 ВОССТАНОВЛЕН // ОБНАРУЖЕН ВНЕШНИЙ ОТВЕТ',8)}
    if(id==='chronicle'){progress.chronicle=true;save();dialog('ХРОНИКА СОЗДАТЕЛЕЙ','Официальная версия',lore.chronicle.text+' Запись добавлена в журнал.')}
    if(id==='rift'){progress.echo=true;save();dialog('ШОВ ПАМЯТИ','Иная последовательность',(progress.ending==='listen'?'Принятый сигнал удерживает голос в фокусе. ':'Изолированный канал оставил отпечаток голоса в спорах. ')+lore.echo2.text+' Запись добавлена в журнал.')}
    if(id==='calibration'){if(!progress.chronicle||!progress.echo){dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Недостаточно данных','Нужны официальная хроника слева и эхо в центре зала.');return}if(progress.seamCalibrated){dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','След исправления',lore.comparison.text);return}dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Найдите противоречие','Метки времени совпадают. Что различается в двух свидетельствах?',[{label:'ПОРЯДОК СОБЫТИЙ',action:()=>{progress.seamCalibrated=true;save();dialog('СОВПАДЕНИЕ НАРУШЕНО','Исправленная хроника',lore.comparison.text+' Арка справа реагирует на восстановленную запись.');goal()}},{label:'ВРЕМЯ СОБЫТИЯ',action:()=>dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Метка совпадает','Обе ленты несут одинаковую метку времени. Вернитесь к пульту и сравните содержание.')},{label:'НАЗВАНИЕ УЗЛА',action:()=>dialog('ПУЛЬТ СОПОСТАВЛЕНИЯ','Адрес совпадает','Обе ленты относятся к Нулевому узлу. Вернитесь к пульту и сравните содержание.')}])}
    if(id==='sealedArch'){if(!progress.seamCalibrated){dialog('ЗАПЕЧАТАННАЯ ВЕТВЬ','Нет согласованного следа','Арка не откроется, пока пульт не сопоставит две записи Разрыва.');return}progress.archSeen=true;save();goal();dialog('ГЛАВА II / ШОВ РАЗРЫВА','Третья запись','Арка открывает лишь узкую щель. За ней виден третий носитель памяти, которого нет в реестре создателей. Сеть не сообщает, кому он принадлежит. Продолжение следует.')}
    if(id==='returnMemory')nextScene('memory');
    if(id==='surface')nextScene('ash');
    if(id==='back')nextScene('atrium');goal()
  }
  function point(e){let r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
  function hit(p){return hotspots[scene].find(h=>p.x>=h.box[0]&&p.x<=h.box[2]&&p.y>=h.box[1]&&p.y<=h.box[3])}
  function walk(x,y,h=null){hero.to={x:Math.max(90,Math.min(1510,x)),y:Math.max(625,Math.min(825,y))};pending=h}
  canvas.addEventListener('pointermove',e=>{hover=hit(point(e));canvas.style.cursor=hover?'pointer':'crosshair'});
  canvas.addEventListener('pointerleave',()=>{hover=null});
  canvas.addEventListener('pointerdown',e=>{if(modal.classList.contains('show')||menu.classList.contains('show')||worldMap.classList.contains('show'))return;let p=point(e),h=hit(p);if(h){walk(h.go[0],h.go[1],h);message(h.name,2)}else if(p.y>560){walk(p.x,p.y);message('Проводник идёт...',1.5)}else message('Здесь нет прохода. Выберите участок пола.',2)});
  function drawHero(){let scale=.68+(hero.y-625)/650,bob=hero.walking&&!settings.reduced?Math.sin(elapsed*12)*2:0,x=hero.x,y=hero.y+bob;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#050c0c99';ctx.beginPath();ctx.ellipse(0,3,29,8,0,0,Math.PI*2);ctx.fill();let sprite=assets.guide;if(sprite&&sprite.complete&&sprite.naturalWidth){ctx.scale(hero.facing,1);ctx.drawImage(sprite,-37,-137,74,137);ctx.restore();return}ctx.lineCap='round';ctx.strokeStyle='#0a1112';ctx.lineWidth=8;let stride=hero.walking&&!settings.reduced?Math.sin(elapsed*12)*8:0;ctx.beginPath();ctx.moveTo(-7,-14);ctx.lineTo(-9+stride,0);ctx.moveTo(7,-14);ctx.lineTo(9-stride,0);ctx.stroke();ctx.fillStyle='#0b1618';ctx.beginPath();ctx.moveTo(-16,-64);ctx.lineTo(14,-63);ctx.lineTo(19,-14);ctx.lineTo(-17,-15);ctx.closePath();ctx.fill();ctx.fillStyle='#34423d';ctx.fillRect(-14,-62,5,41);ctx.fillStyle='#111f23';ctx.beginPath();ctx.ellipse(0,-71,12,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6bbbc2';ctx.fillRect(hero.facing>0?2:-10,-75,8,3);ctx.fillStyle='#c99959';ctx.fillRect(-20,-48,4,11);ctx.restore()}
  function drawHotspots(){for(const h of hotspots[scene]){if(!vision&&!settings.hotspots&&hover!==h)continue;let x=(h.box[0]+h.box[2])/2,y=h.box[3]-32,pulse=settings.reduced?0:3+Math.sin(elapsed*3)*2;ctx.save();ctx.strokeStyle=vision?'#91d2d1':'#ebc58b';ctx.fillStyle=vision?'#b4eceb':'#f8dfaa';ctx.lineWidth=2;ctx.globalAlpha=hover===h?1:.72;ctx.beginPath();ctx.arc(x,y,13+pulse,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();if(hover===h){ctx.font='18px monospace';let measure=ctx.measureText(h.name).width;ctx.fillStyle='#0b181add';ctx.fillRect(x-measure/2-10,y-51,measure+20,30);ctx.fillStyle='#f4e6c8';ctx.fillText(h.name,x-measure/2,y-30)}ctx.restore()}}
  function render(){ctx.fillStyle='#101819';ctx.fillRect(0,0,W,H);let img=assets[scene];if(img&&img.complete&&img.naturalWidth)ctx.drawImage(img,0,0,W,H);ctx.fillStyle='rgba(4,8,4,.30)';ctx.fillRect(0,0,W,H);if(progress.node&&scene==='memory'){ctx.fillStyle='rgba(224,158,75,.08)';ctx.fillRect(0,0,W,H)}drawHotspots();drawHero();if(!settings.reduced)for(let i=0;i<35;i++){let x=(i*317+elapsed*(i%3+1)*8)%W,y=(i*197+Math.sin(elapsed+i)*25)%H;ctx.fillStyle='#dfcc9c60';ctx.fillRect(x,y,2,2)}}
  function update(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;const speed=({slow:180,normal:285,fast:440})[settings.speed]||285;if(!menu.classList.contains('show')&&!modal.classList.contains('show')&&!worldMap.classList.contains('show')){elapsed+=dt;let mx=Number(keys.has('right'))-Number(keys.has('left')),my=Number(keys.has('down'))-Number(keys.has('up'));if(mx||my){hero.to=null;pending=null;let length=Math.hypot(mx,my);hero.x=Math.max(90,Math.min(1510,hero.x+mx/length*speed*dt));hero.y=Math.max(625,Math.min(825,hero.y+my/length*speed*dt));if(mx)hero.facing=mx>0?1:-1;hero.walking=true}else if(hero.to){let dx=hero.to.x-hero.x,dy=hero.to.y-hero.y,d=Math.hypot(dx,dy),step=speed*dt;if(d<=step+3){hero.x=hero.to.x;hero.y=hero.to.y;hero.to=null;hero.walking=false;if(pending){let h=pending;pending=null;interact(h.id)}}else{hero.x+=dx/d*step;hero.y+=dy/d*step;hero.facing=dx>=0?1:-1;hero.walking=true}}else hero.walking=false;if(noticeUntil&&elapsed>noticeUntil){noticeUntil=0;prompt.textContent=vision?'Связи проявились. Выберите отмеченный объект.':'Нажмите на пол, чтобы идти. Осмотрите предметы.'}}render();requestAnimationFrame(update)}
  function load(name,src){return new Promise(resolve=>{let img=new Image();assets[name]=img;img.onload=resolve;img.onerror=()=>{message('Фон не загрузился. Проверьте соединение.',8);resolve()};img.src=src})}
  goal();Promise.all([load('ash','./assets/ash-terraces.webp'),load('atrium','./assets/outer.webp'),load('interface','./assets/coupling-chamber.webp'),load('memory','./assets/vault.webp'),load('seam','./assets/fracture.webp'),load('guide','./assets/mage.webp')]).then(()=>{loading.classList.add('hidden');showMenu();requestAnimationFrame(update)});
})();
