const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'game.js'), 'utf8');
for (const id of ['scene','detail','modal-visual','loading','place','objective','prompt','modal','modal-tag','modal-title','modal-body','modal-choices','vision','journal','close','menu','menu-button','continue','settings-button','new-game','move-speed','text-size','always-hotspots','reduced-motion','world-map','map-button','map-close','map-exits','map-report','pulse','pulse-title','pulse-status','pulse-blocker','pulse-content','pulse-last','pulse-goal','pulse-close','atlas','atlas-button','atlas-image','atlas-title','atlas-close','hero-panel-overlay','hero-button','hero-close','hero-stats']) assert.match(html, new RegExp(`id="${id}"`));
for (const file of ['ash-terraces-cyber.webp','coupling-chamber-cyber.webp','outer-cyber.webp','vault-cyber.webp','fracture-cyber.webp','third-carrier-cyber.webp','salt-hollows.webp','salt-archive.webp','crimson-forest.webp','spore-choir.webp','confluence-ring.webp','living-heart.webp','mage.webp']) {const data=fs.readFileSync(path.join(root,'assets',file));assert.equal(data.toString('ascii',0,4),'RIFF');assert.equal(data.toString('ascii',8,12),'WEBP')}
for(let i=1;i<=14;i++){const data=fs.readFileSync(path.join(root,'assets','atlas',`${String(i).padStart(2,'0')}.webp`));assert.equal(data.toString('ascii',0,4),'RIFF')}
class Element {constructor(){this.textContent='';this.handlers={};this.children=[];this.style={};this.attributes={};this.classList={set:new Set(),add(x){this.set.add(x)},remove(x){this.set.delete(x)},contains(x){return this.set.has(x)},toggle(x,v){if(v===undefined)v=!this.set.has(x);v?this.set.add(x):this.set.delete(x)}}}addEventListener(n,fn){this.handlers[n]=fn}click(){this.handlers.click?.({})}focus(){}setAttribute(k,v){this.attributes[k]=v}replaceChildren(){this.children=[]}append(...x){this.children.push(...x)}querySelector(s){return s==='.map-status'?this.children.find(x=>x.className==='map-status'):null}getBoundingClientRect(){return {left:0,top:0,width:1600,height:900}}}
const nodes=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));
const noop=()=>{};const ctx=new Proxy({}, {get(target,key){if(key==='measureText')return s=>({width:s.length*10});return target[key]||noop},set(target,key,val){target[key]=val;return true}});
nodes.scene.getContext=()=>ctx;
nodes.detail.getContext=()=>ctx;
let raf=null, clock=0;const store={};
if(process.env.TEST_LEGACY)store['cybermycelium-adventure-v1']=JSON.stringify({scene:'seam',ending:'listen',chronicle:true,echo:true,seamCalibrated:true});
const mapNodes=['ash','atrium','interface','memory','seam','carrier','b0','b1','c0','c1','r','center'].map(scene=>Object.assign(new Element(),{dataset:{scene}}));
const tabs=['contour','protocols','echo'].map(pulseTab=>Object.assign(new Element(),{dataset:{pulseTab}}));
const windowHandlers={};const sandbox={document:{body:new Element(),querySelector:s=>s.startsWith('[data-pulse-tab')?tabs[0]:nodes[s.slice(1)],querySelectorAll:s=>s==='.map-node'?mapNodes:s==='[data-pulse-tab]'?tabs:[],createElement:()=>new Element()},window:{addEventListener:(n,fn)=>{windowHandlers[n]=fn}},localStorage:{getItem:k=>store[k],setItem:(k,v)=>store[k]=v},Image:class{set src(v){this.complete=true;this.naturalWidth=1600;this.onload?.()}},requestAnimationFrame:f=>{raf=f},Math,Promise,console};
vm.runInNewContext(js,sandbox,{filename:'game.js'});
const tick=async(n=1)=>{await Promise.resolve();for(let i=0;i<n;i++){clock+=40;raf?.(clock)}};
const at=(x,y)=>nodes.scene.handlers.pointerdown({clientX:x,clientY:y});
const walk=async(x,y)=>{at(x,y);await tick(230)};
const close=()=>nodes.close.click();
const choose=label=>{const button=nodes['modal-choices'].children.find(x=>x.textContent===label);assert(button,`missing action: ${label}`);button.click()};
const protocol=()=>{tabs[1].click();const card=nodes['pulse-content'].children[0];const action=card.children.find(x=>x.textContent==='ПРИМЕНИТЬ');assert(action&&!action.disabled,'protocol unavailable');action.click();nodes['pulse-close'].click()};
const chosenStat=process.env.TEST_STAT||(process.env.TEST_ROUTE==='agility'?'agility':'');
(async()=>{
 await tick();assert(nodes.menu.classList.contains('show'));
 if(process.env.TEST_LEGACY){nodes.continue.click();assert.match(nodes.place.textContent,/ШОВ РАЗРЫВА/);assert(!nodes.modal.classList.contains('show'));await walk(380,600);assert.match(nodes.place.textContent,/СКЛЕП ПАМЯТИ/);await walk(865,385);assert.equal(nodes['modal-title'].textContent,'Путь к Шву');choose('ИДТИ К ШВУ РАЗРЫВА');assert.match(nodes.place.textContent,/ШОВ РАЗРЫВА/);await walk(380,600);await walk(1490,430);assert.match(nodes.place.textContent,/НУЛЕВОЙ УЗЕЛ/);await walk(120,700);assert.match(nodes.place.textContent,/ПЕПЕЛЬНЫЕ ТЕРРАСЫ/);await walk(1350,350);assert.match(nodes.place.textContent,/НУЛЕВОЙ УЗЕЛ/);assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ashPassage,true);console.log('PASS: legacy save resumes with the portal and return path intact');return}
 nodes['settings-button'].click();nodes['move-speed'].value='fast';nodes['move-speed'].handlers.change({target:nodes['move-speed']});nodes['text-size'].value='large';nodes['text-size'].handlers.change({target:nodes['text-size']});nodes['always-hotspots'].checked=true;nodes['always-hotspots'].handlers.change({target:nodes['always-hotspots']});assert.equal(JSON.parse(store['cybermycelium-settings-v1']).speed,'fast');assert(sandbox.document.body.classList.contains('large-text'));
 nodes['settings-back'].click();nodes.continue.click();assert.equal(nodes['modal-title'].textContent,'Пепельные террасы');assert(!nodes.modal.classList.contains('inspect'));close();
 nodes['menu-button'].click();assert(nodes.menu.classList.contains('show'));windowHandlers.keydown({key:'Escape',preventDefault(){}});assert(!nodes.menu.classList.contains('show'));
 nodes['map-button'].click();assert(nodes['world-map'].classList.contains('show'));assert(mapNodes[0].classList.contains('current'));assert(mapNodes[1].classList.contains('locked'));assert.match(nodes['map-exits'].children[0].children[1].textContent,/Сравните свой сигнал/);windowHandlers.keydown({key:'Escape',preventDefault(){}});assert(!nodes['world-map'].classList.contains('show'));
 nodes['atlas-button'].click();assert(nodes.atlas.classList.contains('show'));assert.match(nodes['atlas-image'].src,/01\.webp$/);nodes['atlas-next'].click();assert.match(nodes['atlas-image'].src,/02\.webp$/);nodes['atlas-zoom-in'].click();assert.match(nodes['atlas-image'].style.transform,/1\.25/);windowHandlers.keydown({key:'Escape',preventDefault(){}});assert(!nodes.atlas.classList.contains('show'));
 nodes['hero-button'].click();assert(nodes['hero-panel-overlay'].classList.contains('show'));assert.match(nodes['hero-points'].textContent,/Свободные очки: 6/);if(chosenStat){const index=['strength','intellect','endurance','agility','sensitivity'].indexOf(chosenStat);assert(index>=0);for(let i=0;i<2;i++)nodes['hero-stats'].children[index].children.find(x=>x.textContent==='+').click();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).character.stats[chosenStat],3)}nodes['hero-cloak'].value='cyan';nodes['hero-cloak'].handlers.change({target:nodes['hero-cloak']});nodes['hero-close'].click();
 windowHandlers.keydown({key:'a',preventDefault(){}});await tick(10);windowHandlers.keyup({key:'a'});assert(!nodes.modal.classList.contains('show'));
 await walk(1350,350);assert.equal(nodes['modal-title'].textContent,'Нить без направления');close();
 await walk(120,300);assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ashSignal,false);choose('СЧИТАТЬ ЖУРНАЛ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ashSignal,true);close();
 await walk(820,380);choose(chosenStat==='endurance'?'ДОЛГИЙ КОНТАКТ · ВЫНОСЛИВОСТЬ 3':'СЧИТАТЬ СПОРЫ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ashSpores,true);close();
 await walk(120,300);assert.equal(nodes['modal-title'].textContent,chosenStat==='endurance'?'Сопоставить следы':'Мой ранний сигнал');close();
 await walk(1350,350);assert.equal(nodes['modal-title'].textContent,'Нить без направления');close();
 if(chosenStat!=='endurance'){await walk(820,380);assert.equal(nodes['modal-title'].textContent,'Контакт через споры');choose('ПРИСЛУШАТЬСЯ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).sporeVoice,true);assert.match(nodes['modal-body'].textContent,/нервная система/);close()}
 await walk(120,300);assert.equal(nodes['modal-title'].textContent,'Сопоставить следы');nodes['modal-choices'].children.find(x=>x.textContent==='СОПОСТАВИТЬ РИТМЫ').click();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ashCompared,true);close();
 await walk(1350,350);assert.match(nodes.place.textContent,/НУЛЕВОЙ УЗЕЛ/);
 await walk(1200,600);assert(nodes.pulse.classList.contains('show'));assert.match(nodes['pulse-blocker'].textContent,/переходник/);tabs[1].click();assert(nodes['pulse-content'].children[0].children.find(x=>x.textContent==='ПРИМЕНИТЬ').disabled);nodes['pulse-close'].click();
 await walk(220,350);assert.match(nodes.place.textContent,/КАМЕРА СОПРЯЖЕНИЯ/);
 nodes['map-button'].click();assert(mapNodes[2].classList.contains('current'));assert.match(nodes['map-exits'].children[0].children[1].textContent,/Проход открыт/);assert.equal(mapNodes[0].querySelector('.map-status').textContent,'ПОСЕЩЕНО');nodes['map-close'].click();
 await walk(550,250);assert(nodes.modal.classList.contains('inspect'));choose('СЧИТАТЬ ФАЗЫ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).membraneSeen,true);close();
 await walk(1350,240);choose('ОСМОТРЕТЬ ОЖОГ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).contactsSeen,true);close();
 await walk(1000,430);assert.equal(nodes['modal-title'].textContent,'Собрать переходник');if(chosenStat==='intellect')choose('ВЫВЕСТИ ФАЗЫ · ИНТЕЛЛЕКТ 3');else{choose('ЗАМКНУТЬ КОНТАКТ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).adapter,false);for(const label of ['ИЗОЛИРОВАТЬ','ВЫРОВНЯТЬ РИТМ','ЗАМКНУТЬ КОНТАКТ'])choose(label)}assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).adapter,true);close();
 await walk(120,300);assert.match(nodes.place.textContent,/НУЛЕВОЙ УЗЕЛ/);
 await walk(350,450);assert.equal(nodes['modal-title'].textContent,'Фрагмент 01');choose('СНЯТЬ ЗАПИСЬ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).memory,true);close();
 await walk(850,480);choose('СЧИТАТЬ РЕЕСТР');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).register,true);close();
 await walk(1200,600);assert(nodes.pulse.classList.contains('show'));protocol();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).routePowered,true);
 await walk(1500,500);assert.equal(nodes['modal-title'].textContent,'Настройка у объекта');if(chosenStat==='agility')choose('ПОЙМАТЬ РИТМ · ЛОВКОСТЬ 3');else if(chosenStat==='strength')choose('УДЕРЖАТЬ МЕМБРАНУ · СИЛА 3');else{choose('НАСТРОИТЬ РЕЦЕПТОРЫ');for(const label of ['ТКАНЬ','МЕДЬ','ПАМЯТЬ'])choose(label)}
 assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).relay,true);close();
 await walk(1500,500);assert.match(nodes.place.textContent,/СКЛЕП ПАМЯТИ/);
 await walk(550,450);choose('ЗАПОМНИТЬ ГОЛОС');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).witness,true);close();
 await walk(250,400);choose(chosenStat==='sensitivity'?'РАЗЛИЧИТЬ РИТМ · ЧУТКОСТЬ 3':'СНЯТЬ ОТПЕЧАТОК');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).specimen,true);close();if(chosenStat)assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).buildLocked,true);
 await walk(1200,480);assert(nodes.pulse.classList.contains('show'));protocol();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).signal,true);
 await walk(800,400);assert.equal(nodes['modal-title'].textContent,'Прямое сопряжение');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).node,false);choose('ПОДКЛЮЧИТЬ ПЕРЕХОДНИК');assert.equal(nodes['modal-title'].textContent,'Внешний ответ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).node,true);
 const ending=process.env.TEST_ENDING==='seal'?'seal':'listen';nodes['modal-choices'].children.find(x=>x.textContent===(ending==='seal'?'ИЗОЛИРОВАТЬ':'СЛУШАТЬ ОТВЕТ')).click();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).ending,ending);
 nodes['modal-choices'].children.find(x=>x.textContent==='ИДТИ К ШВУ РАЗРЫВА').click();assert.match(nodes.place.textContent,/ШОВ РАЗРЫВА/);
 nodes['map-button'].click();assert(mapNodes[4].classList.contains('current'));assert(mapNodes[5].classList.contains('locked'));for(const node of mapNodes.slice(6))assert(node.classList.contains('locked'));nodes['map-close'].click();
 await walk(300,300);choose('СНЯТЬ ОТТИСК');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).chronicle,true);close();
 await walk(750,350);choose('ПРОСЛУШАТЬ СЛЕД');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).echo,true);close();
 await walk(1200,450);assert(nodes.pulse.classList.contains('show'));protocol();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).seamReady,true);
 await walk(750,350);assert.equal(nodes['modal-title'].textContent,'Проверить порядок событий');choose('ПОРЯДОК СОБЫТИЙ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).seamCalibrated,true);close();
 await walk(1500,400);choose('ВОЙТИ К НОСИТЕЛЮ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).archSeen,true);assert.match(nodes.place.textContent,/ТРЕТИЙ НОСИТЕЛЬ/);
 nodes['map-button'].click();assert(mapNodes[5].classList.contains('current'));assert.equal(mapNodes[6].querySelector('.map-status').textContent,'ЗАКРЫТО');nodes['map-close'].click();
 await walk(840,340);assert.equal(nodes['modal-title'].textContent,'Недостаточно опор');close();
 await walk(550,525);choose('СЧИТАТЬ ПЕЧАТЬ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).carrierSeal,true);close();
 await walk(1160,490);choose('ПОДАТЬ ПРЯМОЙ ИМПУЛЬС');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).carrierRhythm,false);close();
 await walk(1160,490);choose('СВЕРИТЬ С ПРИБОРОМ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).carrierRhythm,true);close();
 await walk(840,340);choose('Я СОЗДАЛ ЭТУ СЕТЬ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).carrierRead,false);close();
 await walk(840,340);choose('СИГНАЛ СВЯЗАН С МОИМ');assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).carrierRead,true);close();nodes['map-button'].click();for(const id of ['b0','b1','c0','c1'])assert.equal(mapNodes.find(x=>x.dataset.scene===id).querySelector('.map-status').textContent,'ДОСТУПНО');assert.match(nodes['map-exits'].children[1].children[1].textContent,/соляная последовательность/);nodes['map-close'].click();
 await walk(1460,455);assert.equal(nodes['modal-title'].textContent,'Глубина закрыта');assert.match(nodes['modal-body'].textContent,/соляная последовательность/);close();
 await walk(175,385);assert.match(nodes.place.textContent,/ШОВ РАЗРЫВА/);
 await walk(1495,435);assert.match(nodes.place.textContent,/ТРЕТИЙ НОСИТЕЛЬ/);
 nodes.journal.click();assert(!nodes.modal.classList.contains('inspect'));assert.match(nodes['modal-body'].textContent,/Найдено 19 из \d+/);nodes['modal-choices'].children.find(x=>x.textContent==='Прибытие мага').click();assert.match(nodes['modal-body'].textContent,/другой планеты/);nodes['modal-choices'].children.find(x=>x.textContent==='К СПИСКУ').click();nodes['modal-choices'].children.find(x=>x.textContent==='Первый разговор').click();assert.match(nodes['modal-body'].textContent,/через споры/);nodes['modal-choices'].children.find(x=>x.textContent==='К СПИСКУ').click();nodes['modal-choices'].children.find(x=>x.textContent==='Переходник').click();assert.match(nodes['modal-body'].textContent,/биокерамический/);nodes['modal-choices'].children.find(x=>x.textContent==='К СПИСКУ').click();nodes['modal-choices'].children.find(x=>x.textContent==='След Третьего носителя').click();assert.match(nodes['modal-body'].textContent,/независимой проверки/);close();
 nodes.vision.click();assert(nodes.vision.classList.contains('active'));if(chosenStat){nodes['hero-button'].click();assert.match(nodes['hero-points'].textContent,/сборка закреплена/);assert(nodes['hero-stats'].children.every(card=>card.children[2].disabled&&card.children[3].disabled));nodes['hero-close'].click()}
 nodes['menu-button'].click();nodes['new-game'].click();assert.equal(nodes['modal-title'].textContent,'Начать заново?');nodes['modal-choices'].children.find(x=>x.textContent==='СБРОСИТЬ ПРОХОЖДЕНИЕ').click();assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).memory,false);assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).buildLocked,false);assert.equal(JSON.parse(store['cybermycelium-adventure-v1']).scene,'ash');assert.deepEqual(JSON.parse(store['cybermycelium-adventure-v1']).visited,['ash']);assert.equal(JSON.parse(store['cybermycelium-settings-v1']).speed,'fast');
 console.log('PASS: cyberfungal assets, alien mage, map, twelve scenes, coupling room, third carrier, both branches, journal and reset');
})().catch(e=>{console.error(e);process.exitCode=1});
